dlvr_pull_display=function(last.deliverable = 'yyyy-mm-dd hh:mm:ss'){
  
  if(last.deliverable == 'yyyy-mm-dd hh:mm:ss') return('Date of the last deliverable must be given to compute which parameters are updated, deleted, new or already confirmed')

  max.classification = gta_sql_get_value(paste0("SELECT MAX(classification_id) FROM bt_classification_log WHERE time_stamp <= '",last.deliverable,"'"))
  
  if(is.na(max.classification)) return("Prior date is too early or an invalid date has been provided")
  pull.display = paste0("SELECT new_attributes.jurisdiction_name, new_attributes.acting_agency, new_attributes.registration_date, new_attributes.hint_date, new_attributes.english_title, new_attributes.english_description,
                        new_attributes.original_title, new_attributes.original_description, new_attributes.url, new_attributes.hint_id, new_attributes.collection_id, new_attributes.assessment_name, new_attributes.product_group_name, 
                        new_attributes.intervention_type_name, new_attributes.comment, new_attributes.relevance, new_attributes.url_type_id, new_attributes.announcement_date, new_attributes.implementation_date, 
                        new_attributes.removal_date, new_attributes.discard_reason, new_attributes.documentation_status, new_attributes.is_official,
                        (CASE WHEN new_attributes.confirmation_status = 1 THEN 'confirmed' WHEN new_attributes.relevance = 0 THEN 'deleted' WHEN old_attributes.hint_id IS NULL THEN 'new' ELSE 'updated' END) AS confirm_status, new_attributes.is_gta_intervention,
                        CONCAT_WS('','<div class=\"conflicts\"><div class=\"assessment\">Assessment:',new_attributes.conflict_assessment,'</div>','<div class=\"types\">Types:',new_attributes.conflict_intervention_type_name,'</div>','<div class=\"announcement\">Announcement Dates:',new_attributes.conflict_announcement_date,'</div>','<div class=\"implementation\">Implementation Dates:',new_attributes.conflict_implementation_date,'</div>','<div class=\"removal\">Removal Dates:',new_attributes.conflict_removal_date,'</div>','<div class=\"jurisdiction\">Implementer:',new_attributes.conflict_jurisdiction_name,'</div>','<div class=\"product\">Products:',new_attributes.conflict_product_group_name,'</div>','<div class=\"relevance\">Relevance:',new_attributes.conflict_relevance,'</div>','<div class=\"title\">Title:',new_attributes.conflict_title,'</div>','<div class=\"description\">Description:',new_attributes.conflict_description,'</div>','<div class=\"url\">Url:',new_attributes.conflict_url,'</div></div>') AS conflicts,
                        new_attributes.url_classification, new_attributes.text_classification, new_attributes.jur_classification, new_attributes.rlvnt_classification, new_attributes.ass_classification, new_attributes.int_classification, new_attributes.prod_classification, new_attributes.date_classification, new_attributes.discard_classification
                        FROM 
                        (SELECT GROUP_CONCAT(DISTINCT(jur_list.jurisdiction_name) ORDER BY jur_list.jurisdiction_name ASC SEPARATOR ' ; ') AS jurisdiction_name, ht_log.acting_agency, ht_log.registration_date, ht_log.hint_date, 
                        MAX(CASE WHEN ht_txt.language_id=1 THEN ht_txt.hint_title ELSE NULL END) AS english_title,
                        MAX(CASE WHEN ht_txt.language_id=1 THEN ht_txt.hint_description ELSE NULL END) AS english_description, 
                        MAX(CASE WHEN ht_txt.language_id=2 THEN ht_txt.hint_title ELSE NULL END) AS original_title,
                        MAX(CASE WHEN ht_txt.language_id=2 THEN ht_txt.hint_description ELSE NULL END) AS original_description, bt_url_log.url, attributed_hints.hint_id, 
                        GROUP_CONCAT(DISTINCT(cltn_log.collection_id) ORDER BY cltn_log.collection_id ASC SEPARATOR ' ; ') AS collection_id,
                        ass_list.assessment_name, 
                        GROUP_CONCAT(DISTINCT(prod_grp_list.product_group_name) ORDER BY prod_grp_list.product_group_name ASC SEPARATOR ' ; ') AS product_group_name,
                        GROUP_CONCAT(DISTINCT(int_type_list.intervention_type_name) ORDER BY int_type_list.intervention_type_name ASC SEPARATOR ' ; ') AS intervention_type_name,
                        GROUP_CONCAT(DISTINCT(ht_cmt_log.comment) ORDER BY ht_cmt_log.time_stamp DESC SEPARATOR ' ; ') AS comment,
                        ht_rlvnt.relevance, bt_hint_url.url_type_id,
                        MAX(IF(bt_date_type_list.date_type_name='announcement', bt_hint_date.date, NULL )) AS announcement_date,
                        MAX(IF(bt_date_type_list.date_type_name='implementation', bt_hint_date.date, NULL )) AS implementation_date,
                        MAX(IF(bt_date_type_list.date_type_name='removal', bt_hint_date.date, NULL )) AS removal_date,
                        MAX(IF(bt_discard_reason_list.discard_reason_name = 'other (see comment)',bt_hint_discard_reason.discard_reason_comment,bt_discard_reason_list.discard_reason_name)) AS discard_reason,
                        (CASE WHEN bt_hint_documentation_status.hint_id IS NOT NULL THEN dlvr_documentation_status_list.documentation_status_name WHEN MIN(bt_hint_url.url_type_id) = 1 THEN 'Official source' ELSE 'Non-official source' END) AS documentation_status,
                        (CASE WHEN MIN(bt_hint_url.url_type_id) = 1 THEN 1 ELSE 0 END) AS is_official,
                        IF(MIN(bt_hint_url.confirm_status)!=1 OR MIN(ht_txt.confirm_status)!=1 OR MIN(ht_jur.confirm_status)!=1 OR MIN(ht_rlvnt.confirm_status)!=1 OR MIN(ht_ass.confirm_status)!=1 OR MIN(ht_int.confirm_status)!=1 OR MIN(prod_grp.confirm_status)!=1 OR MIN(bt_hint_date.confirm_status)!=1 OR MIN(bt_hint_discard_reason.confirm_status)!=1 OR COALESCE(conflict_ass_list.assessment_name,bt_conflict_date.conflict_date,conflict_int_list.intervention_type_name,conflict_jur_list.jurisdiction_name,conflict_prod_list.product_group_name,bt_conflict_relevance.relevance,bt_conflict_text.conflict_title,conflict_url_log.url) IS NULL,0,1) AS confirmation_status,
                        IF(ht_log.gta_id IS NOT NULL,1,0) AS is_gta_intervention,
                        GROUP_CONCAT(DISTINCT(bt_hint_url.validation_classification) SEPARATOR ' ; ') AS url_classification,
                        GROUP_CONCAT(DISTINCT(ht_txt.validation_classification) SEPARATOR ' ; ') AS text_classification,
                        GROUP_CONCAT(DISTINCT(ht_jur.validation_classification) SEPARATOR ' ; ') AS jur_classification,
                        GROUP_CONCAT(DISTINCT(ht_rlvnt.validation_classification) SEPARATOR ' ; ') AS rlvnt_classification,
                        GROUP_CONCAT(DISTINCT(ht_ass.validation_classification) SEPARATOR ' ; ') AS ass_classification,
                        GROUP_CONCAT(DISTINCT(ht_int.validation_classification) SEPARATOR ' ; ') AS int_classification,
                        GROUP_CONCAT(DISTINCT(prod_grp.validation_classification) SEPARATOR ' ; ') AS prod_classification,
                        GROUP_CONCAT(DISTINCT(bt_hint_date.validation_classification) SEPARATOR ' ; ') AS date_classification,
                        GROUP_CONCAT(DISTINCT(bt_hint_discard_reason.validation_classification) SEPARATOR ' ; ') AS discard_classification,
                        GROUP_CONCAT(DISTINCT(conflict_ass_list.assessment_name) ORDER BY conflict_ass_list.assessment_name ASC SEPARATOR ' ; ') AS conflict_assessment,
                        GROUP_CONCAT(DISTINCT(IF(conflict_date_type.date_type_name='announcement', bt_conflict_date.conflict_date, NULL)) SEPARATOR ' ; ') AS conflict_announcement_date,
                        GROUP_CONCAT(DISTINCT(IF(conflict_date_type.date_type_name='implementation', bt_conflict_date.conflict_date, NULL)) SEPARATOR ' ; ') AS conflict_implementation_date,
                        GROUP_CONCAT(DISTINCT(IF(conflict_date_type.date_type_name='removal', bt_conflict_date.conflict_date, NULL)) SEPARATOR ' ; ') AS conflict_removal_date,
                        GROUP_CONCAT(DISTINCT(conflict_int_list.intervention_type_name) ORDER BY conflict_int_list.intervention_type_name ASC SEPARATOR ' ; ') AS conflict_intervention_type_name,
                        GROUP_CONCAT(DISTINCT(conflict_jur_list.jurisdiction_name) ORDER BY conflict_jur_list.jurisdiction_name ASC SEPARATOR ' ; ') AS conflict_jurisdiction_name,
                        GROUP_CONCAT(DISTINCT(conflict_prod_list.product_group_name) ORDER BY conflict_prod_list.product_group_name ASC SEPARATOR ' ; ') AS conflict_product_group_name,
                        GROUP_CONCAT(DISTINCT(bt_conflict_relevance.relevance) ORDER BY bt_conflict_relevance.relevance ASC SEPARATOR ' ; ') AS conflict_relevance,
                        GROUP_CONCAT(DISTINCT(bt_conflict_text.conflict_title) SEPARATOR ' ; ') AS conflict_title,
                        GROUP_CONCAT(DISTINCT(bt_conflict_text.conflict_description) SEPARATOR ' ; ') AS conflict_description,
                        GROUP_CONCAT(DISTINCT CONCAT_WS(' | ',conflict_url_log.url,(CASE WHEN conflict_url_type_list.url_type_name='official' AND conflict_url_type_list.url_type_name IS NOT NULL THEN 'official' WHEN conflict_url_type_list.url_type_name IS NOT NULL THEN 'non-official' ELSE NULL END)) SEPARATOR ' ; ') AS conflict_url
                        FROM (SELECT DISTINCT hint_id FROM 
                        (SELECT b221_collection_star.hint_id FROM b221_collection_star JOIN bt_hint_log ON b221_collection_star.hint_id = bt_hint_log.hint_id AND bt_hint_log.hint_state_id BETWEEN 3 AND 7
                        UNION 
                        SELECT b221_hint_collection.hint_id FROM b221_hint_collection JOIN bt_hint_log ON b221_hint_collection.hint_id = bt_hint_log.hint_id AND bt_hint_log.hint_state_id BETWEEN 3 AND 7 WHERE NOT EXISTS (SELECT NULL FROM b221_collection_star WHERE b221_collection_star.collection_id = b221_hint_collection.collection_id)
                        UNION 
                        SELECT bt_hint_log.hint_id FROM bt_hint_log WHERE bt_hint_log.hint_state_id BETWEEN 3 AND 7 AND NOT EXISTS (SELECT NULL FROM b221_hint_collection WHERE b221_hint_collection.hint_id = bt_hint_log.hint_id)) attributed_hints) attributed_hints 
                        LEFT JOIN bt_hint_log ht_log ON ht_log.hint_id = attributed_hints.hint_id
                        LEFT JOIN (SELECT bt_hint_url.hint_id, bt_hint_url.url_id, bt_hint_url.url_type_id, bt_hint_url.url_accepted, bt_hint_url.confirm_status, bt_hint_url.validation_classification FROM bt_hint_url JOIN (SELECT bt_hint_url.hint_id, MAX(bt_hint_url.validation_classification) AS newest_classification FROM bt_hint_url GROUP BY hint_id) newest_classification ON newest_classification.hint_id = bt_hint_url.hint_id AND newest_classification.newest_classification <=> bt_hint_url.validation_classification) bt_hint_url ON bt_hint_url.hint_id = attributed_hints.hint_id AND (bt_hint_url.url_accepted = 1 OR bt_hint_url.url_accepted IS NULL)
                        LEFT JOIN bt_url_log ON bt_url_log.url_id = bt_hint_url.url_id
                        LEFT JOIN bt_url_type_list ON bt_hint_url.url_type_id = bt_url_type_list.url_type_id
                        LEFT JOIN (SELECT bt_hint_text.hint_id, bt_hint_text.hint_description, bt_hint_text.language_id, bt_hint_text.description_accepted, bt_hint_text.hint_title, bt_hint_text.confirm_status, bt_hint_text.validation_classification FROM bt_hint_text JOIN (SELECT bt_hint_text.hint_id, MAX(bt_hint_text.validation_classification) AS newest_classification FROM bt_hint_text GROUP BY hint_id) newest_classification ON newest_classification.hint_id = bt_hint_text.hint_id AND newest_classification.newest_classification <=> bt_hint_text.validation_classification) ht_txt ON ht_txt.hint_id = attributed_hints.hint_id AND (ht_txt.description_accepted = 1 OR ht_txt.description_accepted IS NULL) 
                        LEFT JOIN (SELECT bt_hint_jurisdiction.hint_id, bt_hint_jurisdiction.jurisdiction_id, bt_hint_jurisdiction.jurisdiction_accepted, bt_hint_jurisdiction.confirm_status, bt_hint_jurisdiction.validation_classification FROM bt_hint_jurisdiction JOIN (SELECT bt_hint_jurisdiction.hint_id, MAX(bt_hint_jurisdiction.validation_classification) AS newest_classification FROM bt_hint_jurisdiction GROUP BY hint_id) newest_classification ON newest_classification.hint_id = bt_hint_jurisdiction.hint_id AND newest_classification.newest_classification <=> bt_hint_jurisdiction.validation_classification) ht_jur ON ht_jur.hint_id = attributed_hints.hint_id AND (ht_jur.jurisdiction_accepted = 1 OR ht_jur.jurisdiction_accepted IS NULL) LEFT JOIN gta_jurisdiction_list jur_list ON jur_list.jurisdiction_id = ht_jur.jurisdiction_id
                        LEFT JOIN (SELECT bt_hint_relevance.hint_id, bt_hint_relevance.relevance, bt_hint_relevance.relevance_accepted, bt_hint_relevance.confirm_status, bt_hint_relevance.validation_classification FROM bt_hint_relevance JOIN (SELECT bt_hint_relevance.hint_id, MAX(bt_hint_relevance.validation_classification) AS newest_classification FROM bt_hint_relevance GROUP BY hint_id) newest_classification ON newest_classification.hint_id = bt_hint_relevance.hint_id AND newest_classification.newest_classification <=> bt_hint_relevance.validation_classification) ht_rlvnt ON ht_rlvnt.hint_id = attributed_hints.hint_id AND (ht_rlvnt.relevance_accepted = 1 OR ht_rlvnt.relevance_accepted IS NULL)
                        LEFT JOIN b221_hint_collection ht_cltn ON ht_cltn.hint_id = attributed_hints.hint_id LEFT JOIN b221_collection_log cltn_log ON cltn_log.collection_id = ht_cltn.collection_id
                        LEFT JOIN (SELECT b221_hint_assessment.hint_id, b221_hint_assessment.assessment_id, b221_hint_assessment.assessment_accepted, b221_hint_assessment.confirm_status, b221_hint_assessment.validation_classification FROM b221_hint_assessment JOIN (SELECT b221_hint_assessment.hint_id, MAX(b221_hint_assessment.validation_classification) AS newest_classification FROM b221_hint_assessment GROUP BY hint_id) newest_classification ON newest_classification.hint_id = b221_hint_assessment.hint_id AND newest_classification.newest_classification <=> b221_hint_assessment.validation_classification) ht_ass ON ht_ass.hint_id = attributed_hints.hint_id AND (ht_ass.assessment_accepted = 1 OR ht_ass.assessment_accepted IS NULL) LEFT JOIN b221_assessment_list ass_list ON ass_list.assessment_id = ht_ass.assessment_id
                        LEFT JOIN (SELECT b221_hint_product_group.hint_id, b221_hint_product_group.product_group_id, b221_hint_product_group.product_group_assessment, b221_hint_product_group.confirm_status, b221_hint_product_group.validation_classification FROM b221_hint_product_group JOIN (SELECT b221_hint_product_group.hint_id, MAX(b221_hint_product_group.validation_classification) AS newest_classification FROM b221_hint_product_group GROUP BY hint_id) newest_classification ON newest_classification.hint_id = b221_hint_product_group.hint_id AND newest_classification.newest_classification <=> b221_hint_product_group.validation_classification) prod_grp ON prod_grp.hint_id = attributed_hints.hint_id AND (prod_grp.product_group_assessment = 1 OR prod_grp.product_group_assessment IS NULL) LEFT JOIN b221_product_group_list prod_grp_list ON prod_grp_list.product_group_id = prod_grp.product_group_id
                        LEFT JOIN (SELECT b221_hint_intervention.hint_id, b221_hint_intervention.apparent_intervention_id, b221_hint_intervention.intervention_accepted, b221_hint_intervention.confirm_status, b221_hint_intervention.validation_classification FROM b221_hint_intervention JOIN (SELECT b221_hint_intervention.hint_id, MAX(b221_hint_intervention.validation_classification) AS newest_classification FROM b221_hint_intervention GROUP BY hint_id) newest_classification ON newest_classification.hint_id = b221_hint_intervention.hint_id AND newest_classification.newest_classification <=> b221_hint_intervention.validation_classification) ht_int ON ht_int.hint_id = attributed_hints.hint_id AND (ht_int.intervention_accepted = 1 OR ht_int.intervention_accepted IS NULL) LEFT JOIN b221_intervention_type_list int_type_list ON ht_int.apparent_intervention_id = int_type_list.intervention_type_id
                        LEFT JOIN b221_hint_comment_log ht_cmt_log ON ht_cmt_log.hint_id = attributed_hints.hint_id
                        LEFT JOIN (SELECT bt_hint_date.hint_id, bt_hint_date.`date`, bt_hint_date.date_type_id, bt_hint_date.date_accepted, bt_hint_date.confirm_status, bt_hint_date.validation_classification FROM bt_hint_date JOIN (SELECT bt_hint_date.hint_id, MAX(bt_hint_date.validation_classification) AS newest_classification FROM bt_hint_date GROUP BY hint_id) newest_classification ON newest_classification.hint_id = bt_hint_date.hint_id AND newest_classification.newest_classification <=> bt_hint_date.validation_classification) bt_hint_date ON bt_hint_date.hint_id = attributed_hints.hint_id AND (bt_hint_date.date_accepted = 1 OR bt_hint_date.date_accepted IS NULL) LEFT JOIN bt_date_type_list ON bt_hint_date.date_type_id = bt_date_type_list.date_type_id
                        LEFT JOIN (SELECT bt_hint_discard_reason.hint_id, bt_hint_discard_reason.discard_reason_id, bt_hint_discard_reason.discard_reason_comment, bt_hint_discard_reason.reason_accepted, bt_hint_discard_reason.confirm_status, bt_hint_discard_reason.validation_classification FROM bt_hint_discard_reason JOIN (SELECT bt_hint_discard_reason.hint_id, MAX(bt_hint_discard_reason.validation_classification) AS newest_classification FROM bt_hint_discard_reason GROUP BY hint_id) newest_classification ON newest_classification.hint_id = bt_hint_discard_reason.hint_id AND newest_classification.newest_classification <=> bt_hint_discard_reason.validation_classification) bt_hint_discard_reason ON bt_hint_discard_reason.hint_id = attributed_hints.hint_id AND (bt_hint_date.date_accepted = 1 OR bt_hint_discard_reason.reason_accepted IS NULL) LEFT JOIN bt_discard_reason_list ON bt_hint_discard_reason.discard_reason_id = bt_discard_reason_list.discard_reason_id
                        LEFT JOIN bt_hint_documentation_status ON bt_hint_documentation_status.hint_id = attributed_hints.hint_id LEFT JOIN dlvr_documentation_status_list ON dlvr_documentation_status_list.documentation_status_id = bt_hint_documentation_status.documentation_status_id
                        LEFT JOIN bt_conflict_assessment ON attributed_hints.hint_id = bt_conflict_assessment.hint_id AND bt_conflict_assessment.conflict_status = 1 LEFT JOIN b221_assessment_list conflict_ass_list ON conflict_ass_list.assessment_id = bt_conflict_assessment.conflict_assessment_id
                        LEFT JOIN bt_conflict_date ON attributed_hints.hint_id = bt_conflict_date.hint_id AND bt_conflict_date.conflict_status = 1 LEFT JOIN bt_date_type_list conflict_date_type ON conflict_date_type.date_type_id = bt_conflict_date.conflict_date_type_id
                        LEFT JOIN bt_conflict_intervention ON attributed_hints.hint_id = bt_conflict_intervention.hint_id AND bt_conflict_intervention.conflict_status = 1 LEFT JOIN b221_intervention_type_list conflict_int_list ON conflict_int_list.intervention_type_id = bt_conflict_intervention.conflict_intervention_id
                        LEFT JOIN bt_conflict_jurisdiction ON attributed_hints.hint_id = bt_conflict_jurisdiction.hint_id AND bt_conflict_jurisdiction.conflict_status = 1 LEFT JOIN gta_jurisdiction_list conflict_jur_list ON conflict_jur_list.jurisdiction_id = bt_conflict_jurisdiction.conflict_jurisdiction_id
                        LEFT JOIN bt_conflict_product_group ON attributed_hints.hint_id = bt_conflict_product_group.hint_id AND bt_conflict_product_group.conflict_status = 1 LEFT JOIN b221_product_group_list conflict_prod_list ON conflict_prod_list.product_group_id = bt_conflict_product_group.conflict_product_group_id
                        LEFT JOIN bt_conflict_relevance ON attributed_hints.hint_id = bt_conflict_relevance.hint_id AND bt_conflict_relevance.conflict_status = 1 
                        LEFT JOIN bt_conflict_text ON attributed_hints.hint_id = bt_conflict_text.hint_id AND bt_conflict_text.conflict_status = 1
                        LEFT JOIN bt_conflict_url ON attributed_hints.hint_id = bt_conflict_url.hint_id AND bt_conflict_url.conflict_status = 1 LEFT JOIN bt_url_log conflict_url_log ON conflict_url_log.url_id = bt_conflict_url.conflict_url_id LEFT JOIN bt_url_type_list conflict_url_type_list ON conflict_url_type_list.url_type_id = bt_conflict_url.conflict_url_type_id
                        GROUP BY attributed_hints.hint_id) new_attributes
                        LEFT JOIN (SELECT IF(COALESCE(jur_list.jurisdiction_name,prod_grp_list.product_group_name,int_type_list.intervention_type_name,ass_list.assessment_name,bt_url_log.url) IS NULL,NULL,attributed_hints.hint_id) AS hint_id
                        FROM (SELECT DISTINCT hint_id FROM 
                        (SELECT b221_collection_star.hint_id FROM b221_collection_star JOIN bt_hint_log ON b221_collection_star.hint_id = bt_hint_log.hint_id AND bt_hint_log.hint_state_id BETWEEN 3 AND 7
                        UNION 
                        SELECT b221_hint_collection.hint_id FROM b221_hint_collection JOIN bt_hint_log ON b221_hint_collection.hint_id = bt_hint_log.hint_id AND bt_hint_log.hint_state_id BETWEEN 3 AND 7 WHERE NOT EXISTS (SELECT NULL FROM b221_collection_star WHERE b221_collection_star.collection_id = b221_hint_collection.collection_id)
                        UNION 
                        SELECT bt_hint_log.hint_id FROM bt_hint_log WHERE bt_hint_log.hint_state_id BETWEEN 3 AND 7 AND NOT EXISTS (SELECT NULL FROM b221_hint_collection WHERE b221_hint_collection.hint_id = bt_hint_log.hint_id)) attributed_hints) attributed_hints 
                        JOIN bt_hint_log ht_log ON ht_log.hint_id = attributed_hints.hint_id
                        LEFT JOIN (SELECT bt_hint_url.hint_id, bt_hint_url.url_id, bt_hint_url.url_type_id, bt_hint_url.url_accepted, bt_hint_url.confirm_status, bt_hint_url.validation_classification FROM bt_hint_url JOIN (SELECT bt_hint_url.hint_id, MAX(bt_hint_url.validation_classification) AS newest_classification FROM bt_hint_url WHERE bt_hint_url.validation_classification <= ",max.classification," GROUP BY hint_id) newest_classification ON newest_classification.hint_id = bt_hint_url.hint_id AND newest_classification.newest_classification <=> bt_hint_url.validation_classification) bt_hint_url ON bt_hint_url.hint_id = attributed_hints.hint_id AND (bt_hint_url.url_accepted = 1 OR bt_hint_url.url_accepted IS NULL)
                        LEFT JOIN bt_url_log ON bt_url_log.url_id = bt_hint_url.url_id
                        LEFT JOIN bt_url_type_list ON bt_hint_url.url_type_id = bt_url_type_list.url_type_id
                        LEFT JOIN (SELECT bt_hint_text.hint_id, bt_hint_text.hint_description, bt_hint_text.language_id, bt_hint_text.description_accepted, bt_hint_text.hint_title, bt_hint_text.confirm_status, bt_hint_text.validation_classification FROM bt_hint_text JOIN (SELECT bt_hint_text.hint_id, MAX(bt_hint_text.validation_classification) AS newest_classification FROM bt_hint_text WHERE bt_hint_text.validation_classification <= ",max.classification," GROUP BY hint_id) newest_classification ON newest_classification.hint_id = bt_hint_text.hint_id AND newest_classification.newest_classification <=> bt_hint_text.validation_classification) ht_txt ON ht_txt.hint_id = attributed_hints.hint_id AND (ht_txt.description_accepted = 1 OR ht_txt.description_accepted IS NULL) 
                        LEFT JOIN (SELECT bt_hint_jurisdiction.hint_id, bt_hint_jurisdiction.jurisdiction_id, bt_hint_jurisdiction.jurisdiction_accepted, bt_hint_jurisdiction.confirm_status, bt_hint_jurisdiction.validation_classification FROM bt_hint_jurisdiction JOIN (SELECT bt_hint_jurisdiction.hint_id, MAX(bt_hint_jurisdiction.validation_classification) AS newest_classification FROM bt_hint_jurisdiction WHERE bt_hint_jurisdiction.validation_classification <= ",max.classification," GROUP BY hint_id) newest_classification ON newest_classification.hint_id = bt_hint_jurisdiction.hint_id AND newest_classification.newest_classification <=> bt_hint_jurisdiction.validation_classification) ht_jur ON ht_jur.hint_id = attributed_hints.hint_id AND (ht_jur.jurisdiction_accepted = 1 OR ht_jur.jurisdiction_accepted IS NULL) LEFT JOIN gta_jurisdiction_list jur_list ON jur_list.jurisdiction_id = ht_jur.jurisdiction_id
                        LEFT JOIN (SELECT bt_hint_relevance.hint_id, bt_hint_relevance.relevance, bt_hint_relevance.relevance_accepted, bt_hint_relevance.confirm_status, bt_hint_relevance.validation_classification FROM bt_hint_relevance JOIN (SELECT bt_hint_relevance.hint_id, MAX(bt_hint_relevance.validation_classification) AS newest_classification FROM bt_hint_relevance WHERE bt_hint_relevance.validation_classification <= ",max.classification," GROUP BY hint_id) newest_classification ON newest_classification.hint_id = bt_hint_relevance.hint_id AND newest_classification.newest_classification <=> bt_hint_relevance.validation_classification) ht_rlvnt ON ht_rlvnt.hint_id = attributed_hints.hint_id AND (ht_rlvnt.relevance_accepted = 1 OR ht_rlvnt.relevance_accepted IS NULL)
                        LEFT JOIN (SELECT b221_hint_assessment.hint_id, b221_hint_assessment.assessment_id, b221_hint_assessment.assessment_accepted, b221_hint_assessment.confirm_status, b221_hint_assessment.validation_classification FROM b221_hint_assessment JOIN (SELECT b221_hint_assessment.hint_id, MAX(b221_hint_assessment.validation_classification) AS newest_classification FROM b221_hint_assessment WHERE b221_hint_assessment.validation_classification <= ",max.classification," GROUP BY hint_id) newest_classification ON newest_classification.hint_id = b221_hint_assessment.hint_id AND newest_classification.newest_classification <=> b221_hint_assessment.validation_classification) ht_ass ON ht_ass.hint_id = attributed_hints.hint_id AND (ht_ass.assessment_accepted = 1 OR ht_ass.assessment_accepted IS NULL) LEFT JOIN b221_assessment_list ass_list ON ass_list.assessment_id = ht_ass.assessment_id
                        LEFT JOIN (SELECT b221_hint_product_group.hint_id, b221_hint_product_group.product_group_id, b221_hint_product_group.product_group_assessment, b221_hint_product_group.confirm_status, b221_hint_product_group.validation_classification FROM b221_hint_product_group JOIN (SELECT b221_hint_product_group.hint_id, MAX(b221_hint_product_group.validation_classification) AS newest_classification FROM b221_hint_product_group WHERE b221_hint_product_group.validation_classification <= ",max.classification," GROUP BY hint_id) newest_classification ON newest_classification.hint_id = b221_hint_product_group.hint_id AND newest_classification.newest_classification <=> b221_hint_product_group.validation_classification) prod_grp ON prod_grp.hint_id = attributed_hints.hint_id AND (prod_grp.product_group_assessment = 1 OR prod_grp.product_group_assessment IS NULL) LEFT JOIN b221_product_group_list prod_grp_list ON prod_grp_list.product_group_id = prod_grp.product_group_id
                        LEFT JOIN (SELECT b221_hint_intervention.hint_id, b221_hint_intervention.apparent_intervention_id, b221_hint_intervention.intervention_accepted, b221_hint_intervention.confirm_status, b221_hint_intervention.validation_classification FROM b221_hint_intervention JOIN (SELECT b221_hint_intervention.hint_id, MAX(b221_hint_intervention.validation_classification) AS newest_classification FROM b221_hint_intervention WHERE b221_hint_intervention.validation_classification <= ",max.classification," GROUP BY hint_id) newest_classification ON newest_classification.hint_id = b221_hint_intervention.hint_id AND newest_classification.newest_classification <=> b221_hint_intervention.validation_classification) ht_int ON ht_int.hint_id = attributed_hints.hint_id AND (ht_int.intervention_accepted = 1 OR ht_int.intervention_accepted IS NULL) LEFT JOIN b221_intervention_type_list int_type_list ON ht_int.apparent_intervention_id = int_type_list.intervention_type_id
                        GROUP BY attributed_hints.hint_id) old_attributes
                        ON new_attributes.hint_id = old_attributes.hint_id;")  
  
  display=gta_sql_get_value(pull.display)
  return(display)
}


