dlvr_pull_display=function(){
  
    pull.display = paste0("SELECT jur_list.jurisdiction_name, ht_log.acting_agency, ht_log.registration_date, ht_log.hint_date, 
                          MAX(CASE WHEN ht_txt.language_id=1 THEN ht_txt.hint_title ELSE NULL END) AS english_title,
                          MAX(CASE WHEN ht_txt.language_id=1 THEN ht_txt.hint_description ELSE NULL END) AS english_description, 
                          MAX(CASE WHEN ht_txt.language_id=2 THEN ht_txt.hint_title ELSE NULL END) AS original_title,
                          MAX(CASE WHEN ht_txt.language_id=2 THEN ht_txt.hint_description ELSE NULL END) AS original_description, bt_url_log.url, attributed_hints.hint_id, 
                          GROUP_CONCAT(DISTINCT(cltn_log.collection_id) SEPARATOR ' ; ') AS collection_id,
                          ass_list.assessment_name, 
                          GROUP_CONCAT(DISTINCT(prod_grp_list.product_group_name) SEPARATOR ' ; ') AS product_group_name,
                          GROUP_CONCAT(DISTINCT(int_type_list.intervention_type_name) SEPARATOR ' ; ') AS intervention_type_name,
                          GROUP_CONCAT(DISTINCT(ht_cmt_log.comment) ORDER BY ht_cmt_log.time_stamp DESC SEPARATOR ' ; ') AS comment,
                          ht_rlvnt.relevance, bt_hint_url.url_type_id,
                          MAX(IF(bt_date_type_list.date_type_name='announcement', bt_hint_date.date, NULL )) AS announcement_date,
                          MAX(IF(bt_date_type_list.date_type_name='implementation', bt_hint_date.date, NULL )) AS implementation_date,
                          MAX(IF(bt_date_type_list.date_type_name='removal', bt_hint_date.date, NULL )) AS removal_date,
                          MAX(IF(bt_discard_reason_list.discard_reason_name = 'other (see comment)',bt_hint_discard_reason.discard_reason_comment,bt_discard_reason_list.discard_reason_name)) AS discard_reason,
                          (CASE WHEN bt_hint_documentation_status.hint_id IS NOT NULL THEN dlvr_documentation_status_list.documentation_status_name WHEN MIN(bt_hint_url.url_type_id) = 1 THEN (SELECT documentation_status_id FROM dlvr_documentation_status_list WHERE documentation_status_name = 'Official source') ELSE (SELECT documentation_status_id FROM dlvr_documentation_status_list WHERE documentation_status_name = 'Non-official source') END) AS documentation_status,
                          IF(MIN(bt_hint_url.confirm_status)!=1 OR MIN(ht_txt.confirm_status)!=1 OR MIN(ht_jur.confirm_status)!=1 OR MIN(ht_rlvnt.confirm_status)!=1 OR MIN(ht_ass.confirm_status)!=1 OR MIN(ht_int.confirm_status)!=1 OR MIN(prod_grp.confirm_status)!=1 OR MIN(bt_hint_date.confirm_status)!=1 OR MIN(bt_hint_discard_reason.confirm_status)!=1,0,1) AS confirmation_status,
                          GROUP_CONCAT(DISTINCT(bt_hint_url.validation_classification) SEPARATOR ' ; ') AS url_classification,
                          GROUP_CONCAT(DISTINCT(ht_txt.validation_classification) SEPARATOR ' ; ') AS text_classification,
                          GROUP_CONCAT(DISTINCT(ht_jur.validation_classification) SEPARATOR ' ; ') AS jur_classification,
                          GROUP_CONCAT(DISTINCT(ht_rlvnt.validation_classification) SEPARATOR ' ; ') AS rlvnt_classification,
                          GROUP_CONCAT(DISTINCT(ht_ass.validation_classification) SEPARATOR ' ; ') AS ass_classification,
                          GROUP_CONCAT(DISTINCT(ht_int.validation_classification) SEPARATOR ' ; ') AS int_classification,
                          GROUP_CONCAT(DISTINCT(prod_grp.validation_classification) SEPARATOR ' ; ') AS prod_classification,
                          GROUP_CONCAT(DISTINCT(bt_hint_date.validation_classification) SEPARATOR ' ; ') AS date_classification,
                          GROUP_CONCAT(DISTINCT(bt_hint_discard_reason.validation_classification) SEPARATOR ' ; ') AS discard_classification
                          FROM (SELECT bt_hint_log.hint_id FROM bt_hint_log WHERE bt_hint_log.hint_state_id BETWEEN 3 AND 7) attributed_hints 
                          JOIN bt_hint_log ht_log ON ht_log.hint_id = attributed_hints.hint_id
                          JOIN (SELECT bt_hint_url.hint_id, bt_hint_url.url_id, bt_hint_url.url_type_id, bt_hint_url.url_accepted, bt_hint_url.confirm_status, bt_hint_url.validation_classification FROM bt_hint_url JOIN (SELECT bt_hint_url.hint_id, MAX(bt_hint_url.validation_classification) AS newest_classification FROM bt_hint_url GROUP BY hint_id) newest_classification ON newest_classification.hint_id = bt_hint_url.hint_id AND newest_classification.newest_classification <=> bt_hint_url.validation_classification) bt_hint_url ON bt_hint_url.hint_id = attributed_hints.hint_id AND (bt_hint_url.url_accepted = 1 OR bt_hint_url.url_accepted IS NULL)
                          JOIN bt_url_log ON bt_url_log.url_id = bt_hint_url.url_id
                          JOIN bt_url_type_list ON bt_hint_url.url_type_id = bt_url_type_list.url_type_id
                          LEFT JOIN (SELECT bt_hint_text.hint_id, bt_hint_text.hint_description, bt_hint_text.language_id, bt_hint_text.description_accepted, bt_hint_text.hint_title, bt_hint_text.confirm_status, bt_hint_text.validation_classification FROM bt_hint_text JOIN (SELECT bt_hint_text.hint_id, MAX(bt_hint_text.validation_classification) AS newest_classification FROM bt_hint_text GROUP BY hint_id) newest_classification ON newest_classification.hint_id = bt_hint_text.hint_id AND newest_classification.newest_classification <=> bt_hint_text.validation_classification) ht_txt ON ht_txt.hint_id = attributed_hints.hint_id AND (ht_txt.description_accepted = 1 OR ht_txt.description_accepted IS NULL) 
                          LEFT JOIN (SELECT bt_hint_jurisdiction.hint_id, bt_hint_jurisdiction.jurisdiction_id, bt_hint_jurisdiction.jurisdiction_accepted, bt_hint_jurisdiction.confirm_status, bt_hint_jurisdiction.validation_classification FROM bt_hint_jurisdiction JOIN (SELECT bt_hint_jurisdiction.hint_id, MAX(bt_hint_jurisdiction.validation_classification) AS newest_classification FROM bt_hint_jurisdiction GROUP BY hint_id) newest_classification ON newest_classification.hint_id = bt_hint_jurisdiction.hint_id AND newest_classification.newest_classification <=> bt_hint_jurisdiction.validation_classification) ht_jur ON ht_jur.hint_id = attributed_hints.hint_id AND (ht_jur.jurisdiction_accepted = 1 OR ht_jur.jurisdiction_accepted IS NULL) LEFT JOIN gta_jurisdiction_list jur_list ON jur_list.jurisdiction_id = ht_jur.jurisdiction_id
                          LEFT JOIN (SELECT bt_hint_relevance.hint_id, bt_hint_relevance.relevance, bt_hint_relevance.relevance_accepted, bt_hint_relevance.confirm_status, bt_hint_relevance.validation_classification FROM bt_hint_relevance JOIN (SELECT bt_hint_relevance.hint_id, MAX(bt_hint_relevance.validation_classification) AS newest_classification FROM bt_hint_relevance GROUP BY hint_id) newest_classification ON newest_classification.hint_id = bt_hint_relevance.hint_id AND newest_classification.newest_classification <=> bt_hint_relevance.validation_classification) ht_rlvnt ON ht_rlvnt.hint_id = attributed_hints.hint_id AND (ht_rlvnt.relevance_accepted = 1 OR ht_rlvnt.relevance_accepted IS NULL)
                          LEFT JOIN b221_hint_collection ht_cltn ON ht_cltn.hint_id = attributed_hints.hint_id LEFT JOIN b221_collection_log cltn_log ON cltn_log.collection_id = ht_cltn.collection_id
                          LEFT JOIN (SELECT b221_hint_assessment.hint_id, b221_hint_assessment.assessment_id, b221_hint_assessment.assessment_accepted, b221_hint_assessment.confirm_status, b221_hint_assessment.validation_classification FROM b221_hint_assessment JOIN (SELECT b221_hint_assessment.hint_id, MAX(b221_hint_assessment.validation_classification) AS newest_classification FROM b221_hint_assessment GROUP BY hint_id) newest_classification ON newest_classification.hint_id = b221_hint_assessment.hint_id AND newest_classification.newest_classification <=> b221_hint_assessment.validation_classification) ht_ass ON ht_ass.hint_id = attributed_hints.hint_id AND (ht_ass.assessment_accepted = 1 OR ht_ass.assessment_accepted IS NULL) LEFT JOIN b221_assessment_list ass_list ON ass_list.assessment_id = ht_ass.assessment_id
                          LEFT JOIN (SELECT b221_hint_product_group.hint_id, b221_hint_product_group.product_group_id, b221_hint_product_group.product_group_assessment, b221_hint_product_group.confirm_status, b221_hint_product_group.validation_classification FROM b221_hint_product_group JOIN (SELECT b221_hint_product_group.hint_id, MAX(b221_hint_product_group.validation_classification) AS newest_classification FROM b221_hint_product_group GROUP BY hint_id) newest_classification ON newest_classification.hint_id = b221_hint_product_group.hint_id AND newest_classification.newest_classification <=> b221_hint_product_group.validation_classification) prod_grp ON prod_grp.hint_id = attributed_hints.hint_id AND (prod_grp.product_group_assessment = 1 OR prod_grp.product_group_assessment IS NULL) LEFT JOIN b221_product_group_list prod_grp_list ON prod_grp_list.product_group_id = prod_grp.product_group_id
                          LEFT JOIN (SELECT b221_hint_intervention.hint_id, b221_hint_intervention.apparent_intervention_id, b221_hint_intervention.intervention_accepted, b221_hint_intervention.confirm_status, b221_hint_intervention.validation_classification FROM b221_hint_intervention JOIN (SELECT b221_hint_intervention.hint_id, MAX(b221_hint_intervention.validation_classification) AS newest_classification FROM b221_hint_intervention GROUP BY hint_id) newest_classification ON newest_classification.hint_id = b221_hint_intervention.hint_id AND newest_classification.newest_classification <=> b221_hint_intervention.validation_classification) ht_int ON ht_int.hint_id = attributed_hints.hint_id AND (ht_int.intervention_accepted = 1 OR ht_int.intervention_accepted IS NULL) LEFT JOIN b221_intervention_type_list int_type_list ON ht_int.apparent_intervention_id = int_type_list.intervention_type_id
                          LEFT JOIN b221_hint_comment_log ht_cmt_log ON ht_cmt_log.hint_id = attributed_hints.hint_id
                          LEFT JOIN (SELECT bt_hint_date.hint_id, bt_hint_date.`date`, bt_hint_date.date_type_id, bt_hint_date.date_accepted, bt_hint_date.confirm_status, bt_hint_date.validation_classification FROM bt_hint_date JOIN (SELECT bt_hint_date.hint_id, MAX(bt_hint_date.validation_classification) AS newest_classification FROM bt_hint_date GROUP BY hint_id) newest_classification ON newest_classification.hint_id = bt_hint_date.hint_id AND newest_classification.newest_classification <=> bt_hint_date.validation_classification) bt_hint_date ON bt_hint_date.hint_id = attributed_hints.hint_id AND (bt_hint_date.date_accepted = 1 OR bt_hint_date.date_accepted IS NULL) LEFT JOIN bt_date_type_list ON bt_hint_date.date_type_id = bt_date_type_list.date_type_id
                          LEFT JOIN (SELECT bt_hint_discard_reason.hint_id, bt_hint_discard_reason.discard_reason_id, bt_hint_discard_reason.discard_reason_comment, bt_hint_discard_reason.reason_accepted, bt_hint_discard_reason.confirm_status, bt_hint_discard_reason.validation_classification FROM bt_hint_discard_reason JOIN (SELECT bt_hint_discard_reason.hint_id, MAX(bt_hint_discard_reason.validation_classification) AS newest_classification FROM bt_hint_discard_reason GROUP BY hint_id) newest_classification ON newest_classification.hint_id = bt_hint_discard_reason.hint_id AND newest_classification.newest_classification <=> bt_hint_discard_reason.validation_classification) bt_hint_discard_reason ON bt_hint_discard_reason.hint_id = attributed_hints.hint_id AND (bt_hint_date.date_accepted = 1 OR bt_hint_discard_reason.reason_accepted IS NULL) LEFT JOIN bt_discard_reason_list ON bt_hint_discard_reason.discard_reason_id = bt_discard_reason_list.discard_reason_id
                          LEFT JOIN bt_hint_documentation_status ON bt_hint_documentation_status.hint_id = attributed_hints.hint_id LEFT JOIN dlvr_documentation_status_list ON dlvr_documentation_status_list.documentation_status_id = bt_hint_documentation_status.documentation_status_id
                          GROUP BY attributed_hints.hint_id LIMIT 10;")  
  
  
  # cat(pull.display)
  display=gta_sql_get_value(pull.display)
  return(display)
}


